# Generated by Django 6.0.3 on 2026-04-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('payment_type', models.CharField(choices=[('TUITION', 'Tuition Fee'), ('MISC', 'Miscellaneous Fee'), ('LIBRARY', 'Library Fine'), ('OTHER', 'Other')], default='TUITION', max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='PAID', max_length=10)),
                ('reference_number', models.CharField(max_length=30, unique=True)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-date_paid'],
            },
        ),
    ]
